In [1]:
import pandas as pd

In [2]:
# import data
df = pd.read_csv('./ACSDT5Y2024.B19001-Data.csv')
df.head(3)

,GEO_ID,NAME,B19001_001E,B19001_001M,B19001_002E,B19001_002M,B19001_003E,B19001_003M,B19001_004E,B19001_004M,...,B19001_013M,B19001_014E,B19001_014M,B19001_015E,B19001_015M,B19001_016E,B19001_016M,B19001_017E,B19001_017M,Unnamed: 36
0,Geography,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,"Estimate!!Total:!!Less than $10,000","Margin of Error!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Margin of Error!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Margin of Error!!Total:!!$15,000 to $19,999",...,"Margin of Error!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Margin of Error!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Margin of Error!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Margin of Error!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more","Margin of Error!!Total:!!$200,000 or more",NaN
1,1400000US06075010101,Census Tract 101.01; San Francisco County; Cal...,1216,150,78,67,103,64,54,80,...,57,195,123,63,49,149,77,192,101,NaN
2,1400000US06075010102,Census Tract 101.02; San Francisco County; Cal...,930,211,54,52,74,99,0,14,...,42,61,46,68,31,30,34,309,76,NaN

In [3]:
# drop the first column
df = df.drop(df.columns[0], axis=1)
df.head(3)

,NAME,B19001_001E,B19001_001M,B19001_002E,B19001_002M,B19001_003E,B19001_003M,B19001_004E,B19001_004M,B19001_005E,...,B19001_013M,B19001_014E,B19001_014M,B19001_015E,B19001_015M,B19001_016E,B19001_016M,B19001_017E,B19001_017M,Unnamed: 36
0,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,"Estimate!!Total:!!Less than $10,000","Margin of Error!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Margin of Error!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Margin of Error!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999",...,"Margin of Error!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Margin of Error!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Margin of Error!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Margin of Error!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more","Margin of Error!!Total:!!$200,000 or more",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1216,150,78,67,103,64,54,80,100,...,57,195,123,63,49,149,77,192,101,NaN
2,Census Tract 101.02; San Francisco County; Cal...,930,211,54,52,74,99,0,14,35,...,42,61,46,68,31,30,34,309,76,NaN

In [4]:
# change NAME to Area
df = df.rename(columns={'NAME': 'Area'})
df.head(3)

,Area,B19001_001E,B19001_001M,B19001_002E,B19001_002M,B19001_003E,B19001_003M,B19001_004E,B19001_004M,B19001_005E,...,B19001_013M,B19001_014E,B19001_014M,B19001_015E,B19001_015M,B19001_016E,B19001_016M,B19001_017E,B19001_017M,Unnamed: 36
0,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,"Estimate!!Total:!!Less than $10,000","Margin of Error!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Margin of Error!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Margin of Error!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999",...,"Margin of Error!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Margin of Error!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Margin of Error!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Margin of Error!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more","Margin of Error!!Total:!!$200,000 or more",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1216,150,78,67,103,64,54,80,100,...,57,195,123,63,49,149,77,192,101,NaN
2,Census Tract 101.02; San Francisco County; Cal...,930,211,54,52,74,99,0,14,35,...,42,61,46,68,31,30,34,309,76,NaN

In [5]:
# drop the margin columns
df = df[df.columns.drop(list(df.filter(regex='M')))]
df.head(3)

,Area,B19001_001E,B19001_002E,B19001_003E,B19001_004E,B19001_005E,B19001_006E,B19001_007E,B19001_008E,B19001_009E,B19001_010E,B19001_011E,B19001_012E,B19001_013E,B19001_014E,B19001_015E,B19001_016E,B19001_017E,Unnamed: 36
0,Geographic Area Name,Estimate!!Total:,"Estimate!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999","Estimate!!Total:!!$25,000 to $29,999","Estimate!!Total:!!$30,000 to $34,999","Estimate!!Total:!!$35,000 to $39,999","Estimate!!Total:!!$40,000 to $44,999","Estimate!!Total:!!$45,000 to $49,999","Estimate!!Total:!!$50,000 to $59,999","Estimate!!Total:!!$60,000 to $74,999","Estimate!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1216,78,103,54,100,0,0,7,0,47,29,143,56,195,63,149,192,NaN
2,Census Tract 101.02; San Francisco County; Cal...,930,54,74,0,35,56,125,0,19,15,9,19,56,61,68,30,309,NaN

In [6]:
# drop the last column, the header is NaN
df = df.drop(df.columns[-1], axis=1)
df.head(3)

,Area,B19001_001E,B19001_002E,B19001_003E,B19001_004E,B19001_005E,B19001_006E,B19001_007E,B19001_008E,B19001_009E,B19001_010E,B19001_011E,B19001_012E,B19001_013E,B19001_014E,B19001_015E,B19001_016E,B19001_017E
0,Geographic Area Name,Estimate!!Total:,"Estimate!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999","Estimate!!Total:!!$25,000 to $29,999","Estimate!!Total:!!$30,000 to $34,999","Estimate!!Total:!!$35,000 to $39,999","Estimate!!Total:!!$40,000 to $44,999","Estimate!!Total:!!$45,000 to $49,999","Estimate!!Total:!!$50,000 to $59,999","Estimate!!Total:!!$60,000 to $74,999","Estimate!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more"
1,Census Tract 101.01; San Francisco County; Cal...,1216,78,103,54,100,0,0,7,0,47,29,143,56,195,63,149,192
2,Census Tract 101.02; San Francisco County; Cal...,930,54,74,0,35,56,125,0,19,15,9,19,56,61,68,30,309

In [7]:
# rename columns
column_mapping = {}
for i, col in enumerate(df.columns):
    if i < len(df.iloc[0]):  # Make sure we don't go out of bounds
        column_mapping[col] = df.iloc[0, i]

df = df.rename(columns=column_mapping)
df.head(3)

,Geographic Area Name,Estimate!!Total:,"Estimate!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999","Estimate!!Total:!!$25,000 to $29,999","Estimate!!Total:!!$30,000 to $34,999","Estimate!!Total:!!$35,000 to $39,999","Estimate!!Total:!!$40,000 to $44,999","Estimate!!Total:!!$45,000 to $49,999","Estimate!!Total:!!$50,000 to $59,999","Estimate!!Total:!!$60,000 to $74,999","Estimate!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more"
0,Geographic Area Name,Estimate!!Total:,"Estimate!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999","Estimate!!Total:!!$25,000 to $29,999","Estimate!!Total:!!$30,000 to $34,999","Estimate!!Total:!!$35,000 to $39,999","Estimate!!Total:!!$40,000 to $44,999","Estimate!!Total:!!$45,000 to $49,999","Estimate!!Total:!!$50,000 to $59,999","Estimate!!Total:!!$60,000 to $74,999","Estimate!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more"
1,Census Tract 101.01; San Francisco County; Cal...,1216,78,103,54,100,0,0,7,0,47,29,143,56,195,63,149,192
2,Census Tract 101.02; San Francisco County; Cal...,930,54,74,0,35,56,125,0,19,15,9,19,56,61,68,30,309

In [8]:
# remove the first row
df = df.drop(df.index[0])  
df = df.reset_index(drop=True)
df.head(3)

,Geographic Area Name,Estimate!!Total:,"Estimate!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999","Estimate!!Total:!!$25,000 to $29,999","Estimate!!Total:!!$30,000 to $34,999","Estimate!!Total:!!$35,000 to $39,999","Estimate!!Total:!!$40,000 to $44,999","Estimate!!Total:!!$45,000 to $49,999","Estimate!!Total:!!$50,000 to $59,999","Estimate!!Total:!!$60,000 to $74,999","Estimate!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more"
0,Census Tract 101.01; San Francisco County; Cal...,1216,78,103,54,100,0,0,7,0,47,29,143,56,195,63,149,192
1,Census Tract 101.02; San Francisco County; Cal...,930,54,74,0,35,56,125,0,19,15,9,19,56,61,68,30,309
2,Census Tract 102.01; San Francisco County; Cal...,1399,49,6,12,7,63,18,44,16,0,7,88,36,35,204,301,513

In [9]:
# change Geographic Area Name to Area
df = df.rename(columns={'Geographic Area Name': 'Area'})

In [10]:
# only keep numbers for the area column
df['Area'] = df['Area'].str.replace(r'.*Census Tract\s+', '', regex=True)  # remove everything before tract number
df['Area'] = df['Area'].str.replace(r';.*', '', regex=True)  # remove everything after semicolon
df['Area'] = df['Area'].str.strip()  # remove any extra whitespace
df.head(3)

,Area,Estimate!!Total:,"Estimate!!Total:!!Less than $10,000","Estimate!!Total:!!$10,000 to $14,999","Estimate!!Total:!!$15,000 to $19,999","Estimate!!Total:!!$20,000 to $24,999","Estimate!!Total:!!$25,000 to $29,999","Estimate!!Total:!!$30,000 to $34,999","Estimate!!Total:!!$35,000 to $39,999","Estimate!!Total:!!$40,000 to $44,999","Estimate!!Total:!!$45,000 to $49,999","Estimate!!Total:!!$50,000 to $59,999","Estimate!!Total:!!$60,000 to $74,999","Estimate!!Total:!!$75,000 to $99,999","Estimate!!Total:!!$100,000 to $124,999","Estimate!!Total:!!$125,000 to $149,999","Estimate!!Total:!!$150,000 to $199,999","Estimate!!Total:!!$200,000 or more"
0,101.01,1216,78,103,54,100,0,0,7,0,47,29,143,56,195,63,149,192
1,101.02,930,54,74,0,35,56,125,0,19,15,9,19,56,61,68,30,309
2,102.01,1399,49,6,12,7,63,18,44,16,0,7,88,36,35,204,301,513

In [11]:
# get rid of Estimate!!Total:!! in column names
df.columns = df.columns.str.replace('Estimate!!Total:!!', '', regex=True)
df.head(3)

,Area,Estimate!!Total:,"Less than $10,000","$10,000 to $14,999","$15,000 to $19,999","$20,000 to $24,999","$25,000 to $29,999","$30,000 to $34,999","$35,000 to $39,999","$40,000 to $44,999","$45,000 to $49,999","$50,000 to $59,999","$60,000 to $74,999","$75,000 to $99,999","$100,000 to $124,999","$125,000 to $149,999","$150,000 to $199,999","$200,000 or more"
0,101.01,1216,78,103,54,100,0,0,7,0,47,29,143,56,195,63,149,192
1,101.02,930,54,74,0,35,56,125,0,19,15,9,19,56,61,68,30,309
2,102.01,1399,49,6,12,7,63,18,44,16,0,7,88,36,35,204,301,513

In [12]:
# combine a few columns
df['Under $20k'] = df[['Less than $10,000', '$10,000 to $14,999', '$15,000 to $19,999']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['$20-60k'] = df[['$20,000 to $24,999', '$25,000 to $29,999', '$30,000 to $34,999', '$35,000 to $39,999', '$40,000 to $44,999', '$45,000 to $49,999', '$50,000 to $59,999']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['$60-100k'] = df[['$60,000 to $74,999', '$75,000 to $99,999']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['$100-150k'] = df[['$100,000 to $124,999', '$125,000 to $149,999']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['$150-200k'] = df[['$150,000 to $199,999']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['$200k plus'] = df[['$200,000 or more']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
# drop the original columns
columns_to_drop = [
    'Less than $10,000', '$10,000 to $14,999', '$15,000 to $19,999',
    '$20,000 to $24,999', '$25,000 to $29,999', '$30,000 to $34,999',
    '$35,000 to $39,999', '$40,000 to $44,999', '$45,000 to $49,999',
    '$50,000 to $59,999', '$60,000 to $74,999', '$75,000 to $99,999',
    '$100,000 to $124,999', '$125,000 to $149,999', '$150,000 to $199,999',
    '$200,000 or more'
]
df = df.drop(columns=columns_to_drop)
df.head(3)

,Area,Estimate!!Total:,Under $20k,$20-60k,$60-100k,$100-150k,$150-200k,$200k plus
0,101.01,1216,235,183,199,258,149,192
1,101.02,930,128,259,75,129,30,309
2,102.01,1399,67,155,124,239,301,513

In [13]:
# change estimate total column name to Total
df = df.rename(columns={'Estimate!!Total:': 'Total'})
df.head(3)

,Area,Total,Under $20k,$20-60k,$60-100k,$100-150k,$150-200k,$200k plus
0,101.01,1216,235,183,199,258,149,192
1,101.02,930,128,259,75,129,30,309
2,102.01,1399,67,155,124,239,301,513

In [14]:
# convert numeric columns to proper data types
numeric_columns = ['Total', 'Under $20k', '$20-60k', '$60-100k', '$100-150k', '$150-200k', '$200k plus']
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'under $20k': df.set_index('Area')['Under $20k'].to_dict(),
    '$20-60k': df.set_index('Area')['$20-60k'].to_dict(), 
    '$60-100k': df.set_index('Area')['$60-100k'].to_dict(),
    '$100-150k': df.set_index('Area')['$100-150k'].to_dict(),
    '$150-200k': df.set_index('Area')['$150-200k'].to_dict(),
    '$200k plus': df.set_index('Area')['$200k plus'].to_dict(),
    'total': df.set_index('Area')['Total'].to_dict()
}

# convert to JSON and save to file
import json

with open('../../data/income.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'income.json'")

JSON file saved as 'income.json'

Analysis for datawrapper charts

In [ ]:
lookup_df = pd.read_csv('../../data/lookup.csv')

In [17]:
# I want to keep rows where the neighborhood is Inner Richmond, Outer Richmond, or Inner Sunset, Sunset/Parkside, Tenderloin, Bayview Hunters Point, or Mission

neighborhoods_to_keep = ['Inner Richmond', 'Outer Richmond', 'Inner Sunset', 'Sunset/Parkside', 'Tenderloin', 'Bayview Hunters Point', 'Mission']

filtered_lookup_df = lookup_df[lookup_df['neighborhood'].isin(neighborhoods_to_keep)]

In [18]:
filtered_lookup_df

       tract           neighborhood   note
0    9809.00  Bayview Hunters Point  empty
1    9806.00  Bayview Hunters Point  empty
2     612.00  Bayview Hunters Point  empty
3     610.00  Bayview Hunters Point  empty
4     230.03  Bayview Hunters Point  empty
..       ...                    ...    ...
214   124.04             Tenderloin  empty
215   123.01             Tenderloin  empty
216   122.03             Tenderloin  empty
217   122.02             Tenderloin  empty
218   122.04             Tenderloin  empty

[78 rows x 3 columns]

In [20]:
# replace .00 and .0 at the end of the tract numbers with empty string

filtered_lookup_df['tract'] = filtered_lookup_df['tract'].astype(str).str.replace(r'\.0+$', '', regex=True)
filtered_lookup_df['tract'] = filtered_lookup_df['tract'].astype(str).str.replace(r'\.00+$', '', regex=True)
filtered_lookup_df.head(3)

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_86846/689825953.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_lookup_df['tract'] = filtered_lookup_df['tract'].astype(str).str.replace(r'\.0+$', '', regex=True)
/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_86846/689825953.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_lookup_df['tract'] = filtered_lookup_df['tract'].astype(str).str.replace(r'\.00+$', '', regex=True)

  tract           neighborhood   note
0  9809  Bayview Hunters Point  empty
1  9806  Bayview Hunters Point  empty
2   612  Bayview Hunters Point  empty

In [ ]:
richmond_df = filtered_lookup_df[(filtered_lookup_df['neighborhood'] == 'Inner Richmond') | (filtered_lookup_df['neighborhood'] == 'Outer Richmond')]

richmond_df

['452.02',
 '452.01',
 '451',
 '402',
 '401',
 '476',
 '479.04',
 '478.01',
 '426.02',
 '426.01',
 '479.03',
 '479.02',
 '427',
 '477.01',
 '478.02',
 '477.02']

In [24]:
richmond_ids = richmond_df['tract'].tolist()
richmond_ids

['452.02',
 '452.01',
 '451',
 '402',
 '401',
 '476',
 '479.04',
 '478.01',
 '426.02',
 '426.01',
 '479.03',
 '479.02',
 '427',
 '477.01',
 '478.02',
 '477.02']

In [25]:
len(richmond_ids)

16

In [ ]:
# isolate rows in df where Area is in richmond_ids

richmond_income = df[df['Area'].isin(richmond_ids)]

richmond_income

,Area,Total,Under $20k,$20-60k,$60-100k,$100-150k,$150-200k,$200k plus
199,401,1742,98,289,78,321,316,640
200,402,2213,178,213,369,153,200,1100
201,426.01,1735,92,204,388,250,228,573
202,426.02,1367,146,160,161,164,246,490
203,427,2707,406,499,377,450,423,552
205,451,1904,23,268,173,212,205,1023
206,452.01,1324,22,270,92,208,199,533
207,452.02,1489,50,378,213,146,131,571
208,476,2230,103,263,158,418,348,940
209,477.01,2002,244,297,272,387,125,677
210,477.02,1552,180,214,293,289,183,393
211,478.01,1732,102,260,262,189,170,749
212,478.02,1418,91,185,271,258,121,492
213,479.02,1514,149,137,322,221,250,435
214,479.03,1405,125,194,117,268,288,413
215,479.04,1380,157,145,370,154,85,469

In [27]:
# get the sum of each column in richmond_income

richmond_income.sum()

Area          401402426.01426.02427451452.01452.02476477.014...
Total                                                     27714
Under $20k                                                 2166
$20-60k                                                    3976
$60-100k                                                   3916
$100-150k                                                  4088
$150-200k                                                  3518
$200k plus                                                10050
dtype: object

In [29]:
(2166 + 3976) / 27714 * 100

22.162084145197372

In [30]:
(3916 + 4088) / 27714 * 100

28.88071011041351

In [31]:
(3518 + 10050) / 27714 * 100

48.957205744389114

In [32]:
sunset_df = filtered_lookup_df[(filtered_lookup_df['neighborhood'] == 'Inner Sunset') | (filtered_lookup_df['neighborhood'] == 'Sunset/Parkside')]

sunset_df

      tract     neighborhood   note
66   301.01     Inner Sunset  empty
67   303.02     Inner Sunset  empty
68   303.01     Inner Sunset  empty
69   302.02     Inner Sunset  empty
70   302.01     Inner Sunset  empty
71   301.02     Inner Sunset  empty
191     353  Sunset/Parkside  empty
192  352.02  Sunset/Parkside  empty
193  352.01  Sunset/Parkside  empty
194  351.02  Sunset/Parkside  empty
195  351.01  Sunset/Parkside  empty
196     354  Sunset/Parkside  empty
197  326.01  Sunset/Parkside  empty
198     331  Sunset/Parkside  empty
199  330.02  Sunset/Parkside  empty
200  330.01  Sunset/Parkside  empty
201  328.01  Sunset/Parkside  empty
202     327  Sunset/Parkside  empty
203  326.02  Sunset/Parkside  empty
204  329.01  Sunset/Parkside  empty
205  329.02  Sunset/Parkside  empty
206  328.02  Sunset/Parkside  empty

In [34]:
sunset_ids = sunset_df['tract'].tolist()
sunset_ids

['301.01',
 '303.02',
 '303.01',
 '302.02',
 '302.01',
 '301.02',
 '353',
 '352.02',
 '352.01',
 '351.02',
 '351.01',
 '354',
 '326.01',
 '331',
 '330.02',
 '330.01',
 '328.01',
 '327',
 '326.02',
 '329.01',
 '329.02',
 '328.02']

In [35]:
len(sunset_ids)

22

In [36]:
sunset_income = df[df['Area'].isin(sunset_ids)]

sunset_income

,Area,Total,Under $20k,$20-60k,$60-100k,$100-150k,$150-200k,$200k plus
160,301.01,2115,158,221,270,306,574,586
161,301.02,2080,291,82,224,219,190,1074
162,302.01,1922,255,343,288,273,197,566
163,302.02,2041,99,298,569,90,281,704
164,303.01,2552,102,247,294,342,310,1257
165,303.02,1313,84,106,91,237,100,695
180,326.01,1774,229,79,350,189,220,707
181,326.02,1472,70,226,170,209,176,621
182,327,2503,203,469,371,294,293,873
183,328.01,1250,87,197,141,129,267,429
184,328.02,1511,190,246,317,134,95,529
185,329.01,1722,102,218,169,145,382,706
186,329.02,1310,62,147,204,314,202,381
187,330.01,1419,10,100,315,169,203,622
188,330.02,1448,149,62,203,209,170,655
189,331,1383,106,148,110,181,201,637
193,351.01,1452,117,240,179,229,128,559
194,351.02,1259,105,159,103,196,176,520
195,352.01,1915,167,367,230,226,308,617
196,352.02,1677,69,307,349,371,211,370
197,353,2537,417,212,160,395,380,973
198,354,2477,149,321,322,455,464,766

In [38]:
sunset_income.sum()

Area          301.01301.02302.01302.02303.01303.02326.01326....
Total                                                     39132
Under $20k                                                 3221
$20-60k                                                    4795
$60-100k                                                   5429
$100-150k                                                  5312
$150-200k                                                  5528
$200k plus                                                14847
dtype: object

In [39]:
(3221 + 4795) / 39132 * 100

20.48451395277522

In [40]:
(5429 + 5312) / 39132 * 100

27.44812429725033

In [41]:
(5538 + 14847) / 39132 * 100

52.092916283348664