In [538]:
import pandas as pd

In [539]:
# import data
df = pd.read_csv('./ACSDT5Y2024.B03002-Data.csv')
df.head(3)

,GEO_ID,NAME,B03002_001E,B03002_001M,B03002_002E,B03002_002M,B03002_003E,B03002_003M,B03002_004E,B03002_004M,...,B03002_017M,B03002_018E,B03002_018M,B03002_019E,B03002_019M,B03002_020E,B03002_020M,B03002_021E,B03002_021M,Unnamed: 44
0,Geography,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Margin of Error!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Margin of Error!!Total:!!Not Hispanic or Latin...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Margin of Error!!Total:!!Not Hispanic or Latin...,...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,NaN
1,1400000US06075010101,Census Tract 101.01; San Francisco County; Cal...,1911,285,1538,215,717,166,113,124,...,87,121,123,128,93,112,86,16,30,NaN
2,1400000US06075010102,Census Tract 101.02; San Francisco County; Cal...,1917,339,1805,338,617,172,385,322,...,14,79,124,20,23,20,23,0,14,NaN

In [540]:
# drop the first column
df = df.drop(df.columns[0], axis=1)
df.head(3)

,NAME,B03002_001E,B03002_001M,B03002_002E,B03002_002M,B03002_003E,B03002_003M,B03002_004E,B03002_004M,B03002_005E,...,B03002_017M,B03002_018E,B03002_018M,B03002_019E,B03002_019M,B03002_020E,B03002_020M,B03002_021E,B03002_021M,Unnamed: 44
0,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Margin of Error!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Margin of Error!!Total:!!Not Hispanic or Latin...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Margin of Error!!Total:!!Not Hispanic or Latin...,Estimate!!Total:!!Not Hispanic or Latino:!!Ame...,...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,285,1538,215,717,166,113,124,47,...,87,121,123,128,93,112,86,16,30,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,339,1805,338,617,172,385,322,0,...,14,79,124,20,23,20,23,0,14,NaN

In [541]:
# change NAME to Area
df = df.rename(columns={'NAME': 'Area'})
df.head(3)

,Area,B03002_001E,B03002_001M,B03002_002E,B03002_002M,B03002_003E,B03002_003M,B03002_004E,B03002_004M,B03002_005E,...,B03002_017M,B03002_018E,B03002_018M,B03002_019E,B03002_019M,B03002_020E,B03002_020M,B03002_021E,B03002_021M,Unnamed: 44
0,Geographic Area Name,Estimate!!Total:,Margin of Error!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Margin of Error!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Margin of Error!!Total:!!Not Hispanic or Latin...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Margin of Error!!Total:!!Not Hispanic or Latin...,Estimate!!Total:!!Not Hispanic or Latino:!!Ame...,...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Margin of Error!!Total:!!Hispanic or Latino:!!...,NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,285,1538,215,717,166,113,124,47,...,87,121,123,128,93,112,86,16,30,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,339,1805,338,617,172,385,322,0,...,14,79,124,20,23,20,23,0,14,NaN

In [542]:
# drop the margin columns
df = df[df.columns.drop(list(df.filter(regex='M')))]
df.head(3)

,Area,B03002_001E,B03002_002E,B03002_003E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,...,B03002_013E,B03002_014E,B03002_015E,B03002_016E,B03002_017E,B03002_018E,B03002_019E,B03002_020E,B03002_021E,Unnamed: 44
0,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Estimate!!Total:!!Not Hispanic or Latino:!!Ame...,Estimate!!Total:!!Not Hispanic or Latino:!!Asi...,Estimate!!Total:!!Not Hispanic or Latino:!!Nat...,Estimate!!Total:!!Not Hispanic or Latino:!!Som...,Estimate!!Total:!!Not Hispanic or Latino:!!Two...,...,Estimate!!Total:!!Hispanic or Latino:!!White a...,Estimate!!Total:!!Hispanic or Latino:!!Black o...,Estimate!!Total:!!Hispanic or Latino:!!America...,Estimate!!Total:!!Hispanic or Latino:!!Asian a...,Estimate!!Total:!!Hispanic or Latino:!!Native ...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,1538,717,113,47,561,0,62,38,...,51,0,15,0,58,121,128,112,16,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,1805,617,385,0,770,12,0,21,...,13,0,0,0,0,79,20,20,0,NaN

In [543]:
# drop the last column, the header is NaN
df = df.drop(df.columns[-1], axis=1)
df.head(3)

,Area,B03002_001E,B03002_002E,B03002_003E,B03002_004E,B03002_005E,B03002_006E,B03002_007E,B03002_008E,B03002_009E,...,B03002_012E,B03002_013E,B03002_014E,B03002_015E,B03002_016E,B03002_017E,B03002_018E,B03002_019E,B03002_020E,B03002_021E
0,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Estimate!!Total:!!Not Hispanic or Latino:!!Ame...,Estimate!!Total:!!Not Hispanic or Latino:!!Asi...,Estimate!!Total:!!Not Hispanic or Latino:!!Nat...,Estimate!!Total:!!Not Hispanic or Latino:!!Som...,Estimate!!Total:!!Not Hispanic or Latino:!!Two...,...,Estimate!!Total:!!Hispanic or Latino:,Estimate!!Total:!!Hispanic or Latino:!!White a...,Estimate!!Total:!!Hispanic or Latino:!!Black o...,Estimate!!Total:!!Hispanic or Latino:!!America...,Estimate!!Total:!!Hispanic or Latino:!!Asian a...,Estimate!!Total:!!Hispanic or Latino:!!Native ...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...
1,Census Tract 101.01; San Francisco County; Cal...,1911,1538,717,113,47,561,0,62,38,...,373,51,0,15,0,58,121,128,112,16
2,Census Tract 101.02; San Francisco County; Cal...,1917,1805,617,385,0,770,12,0,21,...,112,13,0,0,0,0,79,20,20,0

In [544]:
# rename columns
column_mapping = {}
for i, col in enumerate(df.columns):
    if i < len(df.iloc[0]):  # Make sure we don't go out of bounds
        column_mapping[col] = df.iloc[0, i]

df = df.rename(columns=column_mapping)
df.head(3)

,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!White alone,Estimate!!Total:!!Not Hispanic or Latino:!!Black or African American alone,Estimate!!Total:!!Not Hispanic or Latino:!!American Indian and Alaska Native alone,Estimate!!Total:!!Not Hispanic or Latino:!!Asian alone,Estimate!!Total:!!Not Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone,Estimate!!Total:!!Not Hispanic or Latino:!!Some other race alone,Estimate!!Total:!!Not Hispanic or Latino:!!Two or more races:,...,Estimate!!Total:!!Hispanic or Latino:,Estimate!!Total:!!Hispanic or Latino:!!White alone,Estimate!!Total:!!Hispanic or Latino:!!Black or African American alone,Estimate!!Total:!!Hispanic or Latino:!!American Indian and Alaska Native alone,Estimate!!Total:!!Hispanic or Latino:!!Asian alone,Estimate!!Total:!!Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone,Estimate!!Total:!!Hispanic or Latino:!!Some other race alone,Estimate!!Total:!!Hispanic or Latino:!!Two or more races:,Estimate!!Total:!!Hispanic or Latino:!!Two or more races:!!Two races including Some other race,"Estimate!!Total:!!Hispanic or Latino:!!Two or more races:!!Two races excluding Some other race, and three or more races"
0,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!Whi...,Estimate!!Total:!!Not Hispanic or Latino:!!Bla...,Estimate!!Total:!!Not Hispanic or Latino:!!Ame...,Estimate!!Total:!!Not Hispanic or Latino:!!Asi...,Estimate!!Total:!!Not Hispanic or Latino:!!Nat...,Estimate!!Total:!!Not Hispanic or Latino:!!Som...,Estimate!!Total:!!Not Hispanic or Latino:!!Two...,...,Estimate!!Total:!!Hispanic or Latino:,Estimate!!Total:!!Hispanic or Latino:!!White a...,Estimate!!Total:!!Hispanic or Latino:!!Black o...,Estimate!!Total:!!Hispanic or Latino:!!America...,Estimate!!Total:!!Hispanic or Latino:!!Asian a...,Estimate!!Total:!!Hispanic or Latino:!!Native ...,Estimate!!Total:!!Hispanic or Latino:!!Some ot...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...,Estimate!!Total:!!Hispanic or Latino:!!Two or ...
1,Census Tract 101.01; San Francisco County; Cal...,1911,1538,717,113,47,561,0,62,38,...,373,51,0,15,0,58,121,128,112,16
2,Census Tract 101.02; San Francisco County; Cal...,1917,1805,617,385,0,770,12,0,21,...,112,13,0,0,0,0,79,20,20,0

In [545]:
# remove the first row
df = df.drop(df.index[0])  
df = df.reset_index(drop=True)
df.head(3)

,Geographic Area Name,Estimate!!Total:,Estimate!!Total:!!Not Hispanic or Latino:,Estimate!!Total:!!Not Hispanic or Latino:!!White alone,Estimate!!Total:!!Not Hispanic or Latino:!!Black or African American alone,Estimate!!Total:!!Not Hispanic or Latino:!!American Indian and Alaska Native alone,Estimate!!Total:!!Not Hispanic or Latino:!!Asian alone,Estimate!!Total:!!Not Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone,Estimate!!Total:!!Not Hispanic or Latino:!!Some other race alone,Estimate!!Total:!!Not Hispanic or Latino:!!Two or more races:,...,Estimate!!Total:!!Hispanic or Latino:,Estimate!!Total:!!Hispanic or Latino:!!White alone,Estimate!!Total:!!Hispanic or Latino:!!Black or African American alone,Estimate!!Total:!!Hispanic or Latino:!!American Indian and Alaska Native alone,Estimate!!Total:!!Hispanic or Latino:!!Asian alone,Estimate!!Total:!!Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone,Estimate!!Total:!!Hispanic or Latino:!!Some other race alone,Estimate!!Total:!!Hispanic or Latino:!!Two or more races:,Estimate!!Total:!!Hispanic or Latino:!!Two or more races:!!Two races including Some other race,"Estimate!!Total:!!Hispanic or Latino:!!Two or more races:!!Two races excluding Some other race, and three or more races"
0,Census Tract 101.01; San Francisco County; Cal...,1911,1538,717,113,47,561,0,62,38,...,373,51,0,15,0,58,121,128,112,16
1,Census Tract 101.02; San Francisco County; Cal...,1917,1805,617,385,0,770,12,0,21,...,112,13,0,0,0,0,79,20,20,0
2,Census Tract 102.01; San Francisco County; Cal...,2650,2306,1711,153,55,189,0,10,188,...,344,83,0,0,0,0,15,246,190,56

In [546]:
# change Geographic Area Name to Area
df = df.rename(columns={'Geographic Area Name': 'Area'})

In [547]:
# rename columns
df = df.rename(columns={
    'Estimate!!Total:': 'Citywide',
    'Estimate!!Total:!!Not Hispanic or Latino:': 'Citywide Non-Hispanic or Latino',
    'Estimate!!Total:!!Not Hispanic or Latino:!!White alone': 'White',
    'Estimate!!Total:!!Not Hispanic or Latino:!!Black or African American alone': 'Black',
    'Estimate!!Total:!!Not Hispanic or Latino:!!American Indian and Alaska Native alone': 'Other1',
    'Estimate!!Total:!!Not Hispanic or Latino:!!Asian alone': 'Asian',
    'Estimate!!Total:!!Not Hispanic or Latino:!!Native Hawaiian and Other Pacific Islander alone': 'Other2',
    'Estimate!!Total:!!Not Hispanic or Latino:!!Some other race alone': 'Other3',
    'Estimate!!Total:!!Not Hispanic or Latino:!!Two or more races:': 'Other4',
    'Estimate!!Total:!!Hispanic or Latino:': 'Hispanic or Latino'})
# only keep the columns we want
df = df[['Area', 'Citywide', 'Citywide Non-Hispanic or Latino', 'White', 'Black', 'Other1', 'Asian', 'Other2', 'Other3', 'Other4', 'Hispanic or Latino']]
df.head(3)

,Area,Citywide,Citywide Non-Hispanic or Latino,White,Black,Other1,Asian,Other2,Other3,Other4,Hispanic or Latino
0,Census Tract 101.01; San Francisco County; Cal...,1911,1538,717,113,47,561,0,62,38,373
1,Census Tract 101.02; San Francisco County; Cal...,1917,1805,617,385,0,770,12,0,21,112
2,Census Tract 102.01; San Francisco County; Cal...,2650,2306,1711,153,55,189,0,10,188,344

In [548]:
# convert to numeric and sum in one step
df['Other'] = df[['Other1', 'Other2', 'Other3', 'Other4']].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df.head(3)

,Area,Citywide,Citywide Non-Hispanic or Latino,White,Black,Other1,Asian,Other2,Other3,Other4,Hispanic or Latino,Other
0,Census Tract 101.01; San Francisco County; Cal...,1911,1538,717,113,47,561,0,62,38,373,147
1,Census Tract 101.02; San Francisco County; Cal...,1917,1805,617,385,0,770,12,0,21,112,33
2,Census Tract 102.01; San Francisco County; Cal...,2650,2306,1711,153,55,189,0,10,188,344,253

In [549]:
# only keep the columns we want
df = df[['Area', 'Citywide', 'White', 'Black', 'Asian', 'Hispanic or Latino', 'Other']]
df.head(3)

,Area,Citywide,White,Black,Asian,Hispanic or Latino,Other
0,Census Tract 101.01; San Francisco County; Cal...,1911,717,113,561,373,147
1,Census Tract 101.02; San Francisco County; Cal...,1917,617,385,770,112,33
2,Census Tract 102.01; San Francisco County; Cal...,2650,1711,153,189,344,253

In [550]:
# only keep numbers for the area column
df['Area'] = df['Area'].str.replace(r'.*Census Tract\s+', '', regex=True)  # remove everything before tract number
df['Area'] = df['Area'].str.replace(r';.*', '', regex=True)  # remove everything after semicolon
df['Area'] = df['Area'].str.strip()  # remove any extra whitespace
df

        Area Citywide White Black Asian Hispanic or Latino  Other
0     101.01     1911   717   113   561                373    147
1     101.02     1917   617   385   770                112     33
2     102.01     2650  1711   153   189                344    253
3     102.02     1839  1240    30   277                 51    241
4        103     3824  2238     0   925                435    226
..       ...      ...   ...   ...   ...                ...    ...
239  9805.01      146     0     0   146                  0      0
240     9806     1295   238   285   473                186    113
241     9809      439    80    60   241                 23     35
242     9901        0     0     0     0                  0      0
243     9902        0     0     0     0                  0      0

[244 rows x 7 columns]

In [551]:
# convert numeric columns to proper data types
numeric_columns = ['Citywide', 'White', 'Black', 'Asian', 'Hispanic or Latino', 'Other']
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'white': df.set_index('Area')['White'].to_dict(),
    'asian': df.set_index('Area')['Asian'].to_dict(), 
    'hispanic': df.set_index('Area')['Hispanic or Latino'].to_dict(),
    'black': df.set_index('Area')['Black'].to_dict(),
    'other': df.set_index('Area')['Other'].to_dict(),
    'total': df.set_index('Area')['Citywide'].to_dict()
}

# convert to JSON and save to file
import json

with open('../../data/race.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'race.json'")

JSON file saved as 'race.json'

## Analysis for sunset and richmond

In [552]:
# read lookup.csv that is in ../../data/lookup.csv

lookup_df = pd.read_csv('../../data/lookup.csv')
lookup_df.head(3)

    tract           neighborhood   note
0  9809.0  Bayview Hunters Point  empty
1  9806.0  Bayview Hunters Point  empty
2   612.0  Bayview Hunters Point  empty

In [553]:
# I want the rows in lookup_df where the Neighborhood column is Inner Richmond or Outer Richmond

richmond_lookup_df = lookup_df[lookup_df['neighborhood'].isin(['Inner Richmond', 'Outer Richmond'])]
richmond_lookup_df.head

<bound method NDFrame.head of       tract    neighborhood   note
61   452.02  Inner Richmond  empty
62   452.01  Inner Richmond  empty
63   451.00  Inner Richmond  empty
64   402.00  Inner Richmond  empty
65   401.00  Inner Richmond  empty
143  476.00  Outer Richmond  empty
144  479.04  Outer Richmond  empty
145  478.01  Outer Richmond  empty
146  426.02  Outer Richmond  empty
147  426.01  Outer Richmond  empty
148  479.03  Outer Richmond  empty
149  479.02  Outer Richmond  empty
150  427.00  Outer Richmond  empty
151  477.01  Outer Richmond  empty
152  478.02  Outer Richmond  empty
153  477.02  Outer Richmond  empty>

In [554]:
sunset_lookup_df = lookup_df[lookup_df['neighborhood'].isin(['Inner Sunset', 'Sunset/Parkside'])]

In [555]:
sunset_lookup_df

      tract     neighborhood   note
66   301.01     Inner Sunset  empty
67   303.02     Inner Sunset  empty
68   303.01     Inner Sunset  empty
69   302.02     Inner Sunset  empty
70   302.01     Inner Sunset  empty
71   301.02     Inner Sunset  empty
191  353.00  Sunset/Parkside  empty
192  352.02  Sunset/Parkside  empty
193  352.01  Sunset/Parkside  empty
194  351.02  Sunset/Parkside  empty
195  351.01  Sunset/Parkside  empty
196  354.00  Sunset/Parkside  empty
197  326.01  Sunset/Parkside  empty
198  331.00  Sunset/Parkside  empty
199  330.02  Sunset/Parkside  empty
200  330.01  Sunset/Parkside  empty
201  328.01  Sunset/Parkside  empty
202  327.00  Sunset/Parkside  empty
203  326.02  Sunset/Parkside  empty
204  329.01  Sunset/Parkside  empty
205  329.02  Sunset/Parkside  empty
206  328.02  Sunset/Parkside  empty

In [556]:
# make a list of the tract numbers in richmond_lookup_df and convert to string

richmond_tracts = richmond_lookup_df['tract'].astype(str).tolist()
sunset_tracts = sunset_lookup_df['tract'].astype(str).tolist()

In [557]:
richmond_tracts

['452.02',
 '452.01',
 '451.0',
 '402.0',
 '401.0',
 '476.0',
 '479.04',
 '478.01',
 '426.02',
 '426.01',
 '479.03',
 '479.02',
 '427.0',
 '477.01',
 '478.02',
 '477.02']

In [558]:
sunset_tracts

['301.01',
 '303.02',
 '303.01',
 '302.02',
 '302.01',
 '301.02',
 '353.0',
 '352.02',
 '352.01',
 '351.02',
 '351.01',
 '354.0',
 '326.01',
 '331.0',
 '330.02',
 '330.01',
 '328.01',
 '327.0',
 '326.02',
 '329.01',
 '329.02',
 '328.02']

In [559]:
lookup_df.dtypes

tract           float64
neighborhood     object
note             object
dtype: object

In [560]:
df.dtypes

Area                  object
Citywide               int64
White                  int64
Black                  int64
Asian                  int64
Hispanic or Latino     int64
Other                  int64
dtype: object

In [561]:
# only keep the rows in df where the Area column is in richmond_tracts

richmond_df = df[df['Area'].isin(richmond_tracts)]
sunset_df = df[df['Area'].isin(sunset_tracts)]

In [562]:
richmond_df

       Area  Citywide  White  Black  Asian  Hispanic or Latino  Other
201  426.01      4342   1867     26   1550                 438    461
202  426.02      3202   1468     20   1156                 395    163
206  452.01      3045   1210    130   1194                 286    225
207  452.02      3332   1428     37   1230                 358    279
209  477.01      4724   1327     38   2278                 718    363
210  477.02      3135   1317      1   1450                 166    201
211  478.01      4132   1570     47   1987                 348    180
212  478.02      3581   1355     15   1542                 558    111
213  479.02      3236   1398      0   1083                 521    234
214  479.03      3348   1781     28   1143                 201    195
215  479.04      3077   1550     93    867                 243    324

In [563]:
sunset_df

       Area  Citywide  White  Black  Asian  Hispanic or Latino  Other
160  301.01      4389   1884     93   1477                 478    457
161  301.02      5120   2544    224   1418                 453    481
162  302.01      3841   1892     25   1036                 714    174
163  302.02      4082   1918     65   1341                 276    482
164  303.01      6160   2554    115   2419                 778    294
165  303.02      3552   1307     71   1650                 244    280
180  326.01      4338   1487     41   1913                 624    273
181  326.02      4118   1168    225   1889                 354    482
183  328.01      4021    745     13   2783                 303    177
184  328.02      4268   1085    103   2626                 124    330
185  329.01      6013    975    225   3769                 354    690
186  329.02      3720    654     41   2568                 377     80
187  330.01      3911    668      3   2563                 441    236
188  330.02      4015   1570     24   1732                 341    348
193  351.01      3748   1722    101   1422                 342    161
194  351.02      3755   1123      0   2319                 195    118
195  352.01      5020   1722     20   2649                 279    350
196  352.02      4188   1498     90   1691                 746    163

In [564]:
# get the total for each race and calculate that as a percentage of the citywide total column sum 

richmond_race_totals = richmond_df[['White', 'Black', 'Asian', 'Hispanic or Latino', 'Other']].sum()

richmond_race_percentages = (richmond_race_totals / richmond_df['Citywide'].sum()) * 100

In [565]:
sunset_race_totals = sunset_df[['White', 'Black', 'Asian', 'Hispanic or Latino', 'Other']].sum()

sunset_race_percentages = (sunset_race_totals / sunset_df['Citywide'].sum()) * 100

In [566]:
richmond_race_percentages.round(1)

White                 41.6
Black                  1.1
Asian                 39.5
Hispanic or Latino    10.8
Other                  7.0
dtype: float64

In [567]:
sunset_race_percentages.round(1)

White                 33.9
Black                  1.9
Asian                 47.6
Hispanic or Latino     9.5
Other                  7.1
dtype: float64

## Checking the data

In [568]:
! ls

ACSDT5Y2023.B03002-Column-Metadata.csv
ACSDT5Y2023.B03002-Data.csv
ACSDT5Y2023.B03002-Table-Notes.txt
ACSDT5Y2024.B03002-Column-Metadata.csv
ACSDT5Y2024.B03002-Data.csv
ACSDT5Y2024.B03002-Table-Notes.txt
ACSDT5Y2024.B03002_2026-02-17T182852.zip
TO_CHECK_ACSDT5Y2024.B03002-2026-03-10T195825.csv
race-2024.ipynb

Using TO_CHECK_ACSDT5Y2024.B03002-2026-03-10T195825.csv to see if the results in the tool match the data. 

I downloaded data from the same portal, but instead of donwloading for SF county, I selected the tracts that fall within Bayview Hunter-Points, which I identified using [this](https://data.sfgov.org/Geographic-Locations-and-Boundaries/Analysis-Neighborhoods-2020-census-tracts-assigned/sevw-6tgi/explore/query/SELECT%0A%20%20%60the_geom%60%2C%0A%20%20%60object_id%60%2C%0A%20%20%60state_fp%60%2C%0A%20%20%60county_fp%60%2C%0A%20%20%60tractce%60%2C%0A%20%20%60name%60%2C%0A%20%20%60neighborhoods_analysis_boundaries%60%2C%0A%20%20%60data_loaded_at%60%2C%0A%20%20%60sup_dist_2012%60%2C%0A%20%20%60sup_dist_2022%60%2C%0A%20%20%60data_as_of%60%2C%0A%20%20%60geoid%60%0AWHERE%0A%20%20caseless_eq%28%0A%20%20%20%20%60neighborhoods_analysis_boundaries%60%2C%0A%20%20%20%20%22Bayview%20Hunters%20Point%22%0A%20%20%29/page/filter) census tract shapefile.

In [569]:
file_to_check = 'TO_CHECK_ACSDT5Y2024.B03002-2026-03-10T195825.csv'

In [570]:
file_to_check_df = pd.read_csv(file_to_check)

In [571]:
file_to_check_df.dtypes

Label (Grouping)                                                          object
Census Tract 230.01; San Francisco County; California!!Estimate           object
Census Tract 230.01; San Francisco County; California!!Margin of Error    object
Census Tract 230.03; San Francisco County; California!!Estimate           object
Census Tract 230.03; San Francisco County; California!!Margin of Error    object
Census Tract 231.02; San Francisco County; California!!Estimate           object
Census Tract 231.02; San Francisco County; California!!Margin of Error    object
Census Tract 231.03; San Francisco County; California!!Estimate           object
Census Tract 231.03; San Francisco County; California!!Margin of Error    object
Census Tract 232; San Francisco County; California!!Estimate              object
Census Tract 232; San Francisco County; California!!Margin of Error       object
Census Tract 233; San Francisco County; California!!Estimate              object
Census Tract 233; San Francisco County; California!!Margin of Error       object
Census Tract 234; San Francisco County; California!!Estimate              object
Census Tract 234; San Francisco County; California!!Margin of Error       object
Census Tract 610; San Francisco County; California!!Estimate              object
Census Tract 610; San Francisco County; California!!Margin of Error       object
Census Tract 612; San Francisco County; California!!Estimate              object
Census Tract 612; San Francisco County; California!!Margin of Error       object
Census Tract 9806; San Francisco County; California!!Estimate             object
Census Tract 9806; San Francisco County; California!!Margin of Error      object
Census Tract 9809; San Francisco County; California!!Estimate              int64
Census Tract 9809; San Francisco County; California!!Margin of Error      object
dtype: object

In [572]:
file_to_check_df

# isolate the columns that say Estimate 

estimate_cols = ['Label (Grouping)'] +[col for col in file_to_check_df.columns if 'Estimate' in col and col != 'Total_Estimate'] 

estimate_df = file_to_check_df[estimate_cols]

In [573]:
for col in estimate_df.columns:
    if estimate_df[col].dtype == 'object' and col != 'Label (Grouping)':  # Only apply to object columns
        estimate_df[col] = estimate_df[col].str.replace(',', '').astype(float)

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_86377/970798230.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  estimate_df[col] = estimate_df[col].str.replace(',', '').astype(float)

In [574]:
estimate_df

,Label (Grouping),Census Tract 230.01; San Francisco County; California!!Estimate,Census Tract 230.03; San Francisco County; California!!Estimate,Census Tract 231.02; San Francisco County; California!!Estimate,Census Tract 231.03; San Francisco County; California!!Estimate,Census Tract 232; San Francisco County; California!!Estimate,Census Tract 233; San Francisco County; California!!Estimate,Census Tract 234; San Francisco County; California!!Estimate,Census Tract 610; San Francisco County; California!!Estimate,Census Tract 612; San Francisco County; California!!Estimate,Census Tract 9806; San Francisco County; California!!Estimate,Census Tract 9809; San Francisco County; California!!Estimate
0,Total:,5108.0,3812.0,3231.0,4545.0,3570.0,3818.0,3536.0,4295.0,4086.0,1295.0,439
1,Not Hispanic or Latino:,4333.0,3257.0,2137.0,3453.0,2446.0,3119.0,2385.0,3740.0,2372.0,1109.0,416
2,White alone,529.0,439.0,36.0,56.0,308.0,394.0,114.0,560.0,372.0,238.0,80
3,Black or African American alone,302.0,324.0,1291.0,2145.0,808.0,398.0,905.0,628.0,820.0,285.0,60
4,American Indian and Alaska Native alone,15.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0
5,Asian alone,3341.0,2287.0,378.0,598.0,1166.0,2083.0,955.0,2431.0,1124.0,473.0,241
6,Native Hawaiian and Other Pacific Isla...,0.0,25.0,0.0,413.0,8.0,0.0,5.0,0.0,0.0,0.0,0
7,Some other race alone,0.0,0.0,0.0,0.0,8.0,17.0,15.0,26.0,0.0,22.0,0
8,Two or more races:,146.0,182.0,432.0,241.0,148.0,227.0,386.0,95.0,56.0,91.0,35
9,Two races including Some other race,101.0,21.0,55.0,50.0,57.0,18.0,20.0,0.0,0.0,0.0,4
10,Two races excluding Some other rac...,45.0,161.0,377.0,191.0,91.0,209.0,366.0,95.0,56.0,91.0,31
11,Hispanic or Latino:,775.0,555.0,1094.0,1092.0,1124.0,699.0,1151.0,555.0,1714.0,186.0,23
12,White alone,34.0,0.0,99.0,0.0,156.0,134.0,11.0,85.0,58.0,8.0,12
13,Black or African American alone,0.0,0.0,279.0,94.0,0.0,21.0,0.0,0.0,0.0,0.0,0
14,American Indian and Alaska Native alone,119.0,0.0,0.0,48.0,8.0,0.0,0.0,0.0,0.0,45.0,0
15,Asian alone,0.0,0.0,0.0,36.0,2.0,12.0,16.0,0.0,0.0,0.0,0
16,Native Hawaiian and Other Pacific Isla...,0.0,0.0,0.0,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0
17,Some other race alone,482.0,374.0,638.0,639.0,879.0,447.0,812.0,175.0,1435.0,71.0,11
18,Two or more races:,140.0,181.0,78.0,189.0,79.0,85.0,312.0,295.0,221.0,62.0,0
19,Two races including Some other race,140.0,181.0,68.0,171.0,62.0,37.0,269.0,253.0,221.0,56.0,0
20,Two races excluding Some other rac...,0.0,0.0,10.0,18.0,17.0,48.0,43.0,42.0,0.0,6.0,0

In [575]:
# I want to add every value at row 0 and add them together in a Total column, same for row 1, etc.

estimate_df['Total'] = estimate_df.sum(axis=1)

estimate_df

/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_86377/78608169.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  estimate_df['Total'] = estimate_df.sum(axis=1)
/var/folders/_0/x7xh_2c16jq4chdcqrg28fr40000gn/T/ipykernel_86377/78608169.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  estimate_df['Total'] = estimate_df.sum(axis=1)

,Label (Grouping),Census Tract 230.01; San Francisco County; California!!Estimate,Census Tract 230.03; San Francisco County; California!!Estimate,Census Tract 231.02; San Francisco County; California!!Estimate,Census Tract 231.03; San Francisco County; California!!Estimate,Census Tract 232; San Francisco County; California!!Estimate,Census Tract 233; San Francisco County; California!!Estimate,Census Tract 234; San Francisco County; California!!Estimate,Census Tract 610; San Francisco County; California!!Estimate,Census Tract 612; San Francisco County; California!!Estimate,Census Tract 9806; San Francisco County; California!!Estimate,Census Tract 9809; San Francisco County; California!!Estimate,Total
0,Total:,5108.0,3812.0,3231.0,4545.0,3570.0,3818.0,3536.0,4295.0,4086.0,1295.0,439,37735.0
1,Not Hispanic or Latino:,4333.0,3257.0,2137.0,3453.0,2446.0,3119.0,2385.0,3740.0,2372.0,1109.0,416,28767.0
2,White alone,529.0,439.0,36.0,56.0,308.0,394.0,114.0,560.0,372.0,238.0,80,3126.0
3,Black or African American alone,302.0,324.0,1291.0,2145.0,808.0,398.0,905.0,628.0,820.0,285.0,60,7966.0
4,American Indian and Alaska Native alone,15.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0,20.0
5,Asian alone,3341.0,2287.0,378.0,598.0,1166.0,2083.0,955.0,2431.0,1124.0,473.0,241,15077.0
6,Native Hawaiian and Other Pacific Isla...,0.0,25.0,0.0,413.0,8.0,0.0,5.0,0.0,0.0,0.0,0,451.0
7,Some other race alone,0.0,0.0,0.0,0.0,8.0,17.0,15.0,26.0,0.0,22.0,0,88.0
8,Two or more races:,146.0,182.0,432.0,241.0,148.0,227.0,386.0,95.0,56.0,91.0,35,2039.0
9,Two races including Some other race,101.0,21.0,55.0,50.0,57.0,18.0,20.0,0.0,0.0,0.0,4,326.0
10,Two races excluding Some other rac...,45.0,161.0,377.0,191.0,91.0,209.0,366.0,95.0,56.0,91.0,31,1713.0
11,Hispanic or Latino:,775.0,555.0,1094.0,1092.0,1124.0,699.0,1151.0,555.0,1714.0,186.0,23,8968.0
12,White alone,34.0,0.0,99.0,0.0,156.0,134.0,11.0,85.0,58.0,8.0,12,597.0
13,Black or African American alone,0.0,0.0,279.0,94.0,0.0,21.0,0.0,0.0,0.0,0.0,0,394.0
14,American Indian and Alaska Native alone,119.0,0.0,0.0,48.0,8.0,0.0,0.0,0.0,0.0,45.0,0,220.0
15,Asian alone,0.0,0.0,0.0,36.0,2.0,12.0,16.0,0.0,0.0,0.0,0,66.0
16,Native Hawaiian and Other Pacific Isla...,0.0,0.0,0.0,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0,86.0
17,Some other race alone,482.0,374.0,638.0,639.0,879.0,447.0,812.0,175.0,1435.0,71.0,11,5963.0
18,Two or more races:,140.0,181.0,78.0,189.0,79.0,85.0,312.0,295.0,221.0,62.0,0,1642.0
19,Two races including Some other race,140.0,181.0,68.0,171.0,62.0,37.0,269.0,253.0,221.0,56.0,0,1458.0
20,Two races excluding Some other rac...,0.0,0.0,10.0,18.0,17.0,48.0,43.0,42.0,0.0,6.0,0,184.0

Percentage of "white alone" in Bayview Hunter-Point:

In [578]:
3126.0 / 37735.0 * 100

8.28408639194382

Percentage of "asian alone" in Bayview Hunter-Point:

In [579]:
15077.0 / 37735.0 * 100

39.95494898635219

Percentage of "hispanic" in Bayview Hunter-Point:

In [580]:
8968.0 / 37735.0 * 100

23.765734729031404

Percentage of "Black or African American alone" in Bayview Hunter-Point:

In [582]:
7966.0 / 37735.0 * 100

21.110374983437126

Reverse engineering what the "other" category is:

In [583]:
3126.0 + 15077.0 + 8968.0 + 7966.0

35137.0

In [584]:
37735.0 - 35137.0

2598.0

In [585]:
2598.0 / 37735.0 * 100

6.884854909235457