In [573]:
import pandas as pd

In [574]:
# import crime data
df = pd.read_csv('./crime-2025.csv')

In [575]:
# display all columns
pd.set_option('display.max_columns', None)

In [576]:
# initial look
df.head(3)

,Row ID,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,data_as_of,data_loaded_at
0,151187519022,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2025/09/15 11:02:00 AM,1511875,250518633,252581289.0,II,Initial,NaN,19022,Disorderly Conduct,Disorderly Conduct,Disturbing The Peace,Open or Active,ELLIS ST \ FILLMORE ST,26586000.0,Northern,Western Addition,5.0,5.0,37.782349,-122.432518,POINT (-122.432518005 37.782348633),2025/09/16 09:36:50 AM,2025/09/17 09:52:57 AM
1,151187564011,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2025/09/15 11:02:00 AM,1511875,250518633,252581289.0,II,Initial,NaN,64011,Non-Criminal,Other,"Dog, Barking",Open or Active,ELLIS ST \ FILLMORE ST,26586000.0,Northern,Western Addition,5.0,5.0,37.782349,-122.432518,POINT (-122.432518005 37.782348633),2025/09/16 09:36:50 AM,2025/09/17 09:52:57 AM
2,151226575030,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2025/09/17 12:00:00 AM,1512265,250453879,NaN,IS,Initial Supplement,NaN,75030,Case Closure,Case Closure,Case Closure,Cite or Arrest Adult,14TH ST \ HARRISON ST,33033000.0,Mission,Mission,9.0,9.0,37.768673,-122.413399,POINT (-122.413398743 37.768672943),2025/09/18 09:36:39 AM,2025/09/19 09:55:14 AM

In [577]:
# print all columns names
print(df.columns.tolist())

['Row ID', 'Incident Datetime', 'Incident Date', 'Incident Time', 'Incident Year', 'Incident Day of Week', 'Report Datetime', 'Incident ID', 'Incident Number', 'CAD Number', 'Report Type Code', 'Report Type Description', 'Filed Online', 'Incident Code', 'Incident Category', 'Incident Subcategory', 'Incident Description', 'Resolution', 'Intersection', 'CNN', 'Police District', 'Analysis Neighborhood', 'Supervisor District', 'Supervisor District 2012', 'Latitude', 'Longitude', 'Point', 'data_as_of', 'data_loaded_at']

In [578]:
# get shape of the dataframe
print(df.shape)

(93995, 29)

In [579]:
# drop the rows where the Latitude or Longitude is NaN
df = df.dropna(subset=['Latitude', 'Longitude'])
print(df.shape)

(89649, 29)

In [580]:
df.head(3)

,Row ID,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,data_as_of,data_loaded_at
0,151187519022,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2025/09/15 11:02:00 AM,1511875,250518633,252581289.0,II,Initial,NaN,19022,Disorderly Conduct,Disorderly Conduct,Disturbing The Peace,Open or Active,ELLIS ST \ FILLMORE ST,26586000.0,Northern,Western Addition,5.0,5.0,37.782349,-122.432518,POINT (-122.432518005 37.782348633),2025/09/16 09:36:50 AM,2025/09/17 09:52:57 AM
1,151187564011,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2025/09/15 11:02:00 AM,1511875,250518633,252581289.0,II,Initial,NaN,64011,Non-Criminal,Other,"Dog, Barking",Open or Active,ELLIS ST \ FILLMORE ST,26586000.0,Northern,Western Addition,5.0,5.0,37.782349,-122.432518,POINT (-122.432518005 37.782348633),2025/09/16 09:36:50 AM,2025/09/17 09:52:57 AM
2,151226575030,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2025/09/17 12:00:00 AM,1512265,250453879,NaN,IS,Initial Supplement,NaN,75030,Case Closure,Case Closure,Case Closure,Cite or Arrest Adult,14TH ST \ HARRISON ST,33033000.0,Mission,Mission,9.0,9.0,37.768673,-122.413399,POINT (-122.413398743 37.768672943),2025/09/18 09:36:39 AM,2025/09/19 09:55:14 AM

In [581]:
# get a list of the unique Incident Category
incident_categories = df['Incident Category'].unique()
print(incident_categories)

['Disorderly Conduct' 'Non-Criminal' 'Case Closure' 'Robbery' 'Fraud'
 'Motor Vehicle Theft' 'Malicious Mischief' 'Forgery And Counterfeiting'
 'Miscellaneous Investigation' 'Offences Against The Family And Children'
 'Missing Person' 'Weapons Offense' 'Larceny Theft' 'Lost Property'
 'Other Offenses' 'Assault' 'Recovered Vehicle' 'Weapons Carrying Etc'
 'Other Miscellaneous' 'Burglary' 'Warrant' 'Drug Offense' 'Arson'
 'Courtesy Report' 'Suspicious Occ' 'Other' 'Gambling'
 'Traffic Violation Arrest' 'Vehicle Impounded' 'Traffic Collision'
 'Vandalism' 'Drug Violation' 'Stolen Property' nan 'Homicide'
 'Embezzlement' 'Vehicle Misplaced' 'Sex Offense' 'Fire Report' 'Suicide'
 'Rape' 'Suspicious' 'Prostitution' 'Motor Vehicle Theft?' 'Liquor Laws'
 'Human Trafficking, Commercial Sex Acts' 'Civil Sidewalks'
 'Weapons Offence' 'Human Trafficking (A), Commercial Sex Acts']

I only want: Assault, Burglary, Larceny, Motor vehicle theft, Robbery.

In [582]:
# define the categories to keep and consolidate
assault_cats = ['Assault']
burglary_cats = ['Burglary']
larceny_cats = ['Larceny Theft', 'Embezzlement', 'Stolen Property']
mv_theft_cats = ['Motor Vehicle Theft', 'Motor Vehicle Theft?']
robbery_cats = ['Robbery']

In [583]:
# create a list of all categories to keep
keep_categories = assault_cats + burglary_cats + larceny_cats + mv_theft_cats + robbery_cats

In [584]:
# filter your dataframe
filtered_df = df[df['Incident Category'].isin(keep_categories)].copy()

In [585]:
filtered_df.shape[0]

36561

In [586]:
filtered_df['Incident Category'].value_counts()

Larceny Theft           18473
Assault                  7177
Burglary                 4472
Motor Vehicle Theft      4059
Robbery                  1839
Stolen Property           441
Embezzlement               89
Motor Vehicle Theft?       11
Name: Incident Category, dtype: int64

In [587]:
# group by report type description and incident category, then count the number of occurrences

grouped = filtered_df.groupby(['Report Type Description', 'Incident Category']).size().reset_index(name='Count')

grouped

   Report Type Description     Incident Category  Count
0         Coplogic Initial              Burglary      2
1         Coplogic Initial         Larceny Theft   8102
2      Coplogic Supplement              Burglary    197
3      Coplogic Supplement         Larceny Theft    402
4                  Initial               Assault   6452
5                  Initial              Burglary   3666
6                  Initial          Embezzlement     34
7                  Initial         Larceny Theft   8115
8                  Initial   Motor Vehicle Theft    286
9                  Initial  Motor Vehicle Theft?      5
10                 Initial               Robbery   1543
11                 Initial       Stolen Property    292
12      Initial Supplement               Assault    724
13      Initial Supplement              Burglary    559
14      Initial Supplement          Embezzlement     11
15      Initial Supplement         Larceny Theft    675
16      Initial Supplement   Motor Vehicle Theft    147
17      Initial Supplement  Motor Vehicle Theft?      3
18      Initial Supplement               Robbery    262
19      Initial Supplement       Stolen Property    144
20         Vehicle Initial               Assault      1
21         Vehicle Initial              Burglary     18
22         Vehicle Initial          Embezzlement     40
23         Vehicle Initial         Larceny Theft   1154
24         Vehicle Initial   Motor Vehicle Theft   3404
25         Vehicle Initial  Motor Vehicle Theft?      1
26         Vehicle Initial               Robbery     24
27         Vehicle Initial       Stolen Property      2
28      Vehicle Supplement              Burglary     30
29      Vehicle Supplement          Embezzlement      4
30      Vehicle Supplement         Larceny Theft     25
31      Vehicle Supplement   Motor Vehicle Theft    222
32      Vehicle Supplement  Motor Vehicle Theft?      2
33      Vehicle Supplement               Robbery     10
34      Vehicle Supplement       Stolen Property      3

In [588]:
# filter filtered_df to only include rows where the Report Type Description is "Incident Report"
filtered_df = filtered_df[(filtered_df['Report Type Description'] == 'Initial') | (filtered_df['Report Type Description'] == 'Vehicle Initial')]

In [589]:
filtered_df.shape[0]

25037

In [590]:
filtered_df['Incident Category'].value_counts()

Larceny Theft           9269
Assault                 6453
Motor Vehicle Theft     3690
Burglary                3684
Robbery                 1567
Stolen Property          294
Embezzlement              74
Motor Vehicle Theft?       6
Name: Incident Category, dtype: int64

In [591]:
# create a new consolidated category column
def consolidate_category(category):
    if category in assault_cats:
        return 'Assault'
    elif category in burglary_cats:
        return 'Burglary'
    elif category in larceny_cats:
        return 'Larceny'
    elif category in mv_theft_cats:
        return 'Motor Vehicle Theft'
    elif category in robbery_cats:
        return 'Robbery'
    else:
        return category

filtered_df['Consolidated Category'] = filtered_df['Incident Category'].apply(consolidate_category)

In [592]:
# check the results
filtered_df['Consolidated Category'].value_counts()

Larceny                9637
Assault                6453
Motor Vehicle Theft    3696
Burglary               3684
Robbery                1567
Name: Consolidated Category, dtype: int64

In [593]:
filtered_df

,Row ID,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,data_as_of,data_loaded_at,Consolidated Category
5,151652107026,2025/01/01 08:00:00 PM,2025/01/01,20:00,2025,Wednesday,2025/10/04 09:06:00 AM,1516521,250558736,252770881.0,VI,Vehicle Initial,NaN,7026,Motor Vehicle Theft,Motor Vehicle Theft,"Vehicle, Stolen, Other Vehicle",Open or Active,FELL ST \ VAN NESS AVE,24448000.0,Southern,Hayes Valley,5.0,5.0,37.776367,-122.419510,POINT (-122.419509888 37.776367188),2025/10/05 09:35:21 AM,2025/10/06 09:56:49 AM,Motor Vehicle Theft
18,153673706243,2025/01/01 06:00:00 PM,2025/01/01,18:00,2025,Wednesday,2026/01/02 01:32:00 PM,1536737,260002739,260021707.0,II,Initial,NaN,6243,Larceny Theft,Larceny - From Vehicle,"Theft, From Locked Vehicle, $200-$950",Open or Active,GEARY BLVD \ WOOD ST,26905000.0,Richmond,Lone Mountain/USF,2.0,1.0,37.782177,-122.449051,POINT (-122.449050903 37.782176971),2026/01/03 09:36:05 AM,2026/01/04 09:56:27 AM,Larceny
22,153876807021,2025/01/01 08:00:00 PM,2025/01/01,20:00,2025,Wednesday,2026/01/11 06:00:00 PM,1538768,260020220,260112501.0,VI,Vehicle Initial,NaN,7021,Motor Vehicle Theft,Motor Vehicle Theft,"Vehicle, Stolen, Auto",Open or Active,24TH ST \ DIAMOND ST,25760000.0,Mission,Noe Valley,8.0,8.0,37.751152,-122.436302,POINT (-122.436302185 37.751152039),2026/01/12 09:38:08 AM,2026/01/13 10:06:12 AM,Motor Vehicle Theft
29,145115604134,2025/01/01 05:05:00 AM,2025/01/01,05:05,2025,Wednesday,2025/01/01 05:14:00 AM,1451156,250000442,250010826.0,II,Initial,NaN,4134,Assault,Simple Assault,Battery,Open or Active,CASTILLO ST \ VELASCO AVE,20412000.0,Taraval,Visitacion Valley,10.0,10.0,37.709473,-122.417656,POINT (-122.417655945 37.709472656),2025/06/12 10:07:02 AM,2025/06/13 09:52:57 AM,Assault
30,145112004138,2025/01/01 12:40:00 AM,2025/01/01,00:40,2025,Wednesday,2025/01/01 12:40:00 AM,1451120,250000088,250010170.0,II,Initial,NaN,4138,Assault,Simple Assault,"Battery, former Spouse or Dating Relationship",Cite or Arrest Adult,03RD ST \ MINNA ST,24609000.0,Southern,Financial District/South Beach,6.0,6.0,37.785828,-122.401489,POINT (-122.401489258 37.785827637),2025/06/12 10:07:02 AM,2025/06/13 09:52:57 AM,Assault
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93944,153736006301,2025/12/31 10:24:00 AM,2025/12/31,10:24,2025,Wednesday,2026/01/05 12:25:00 PM,1537360,260007397,260051451.0,II,Initial,NaN,6301,Larceny Theft,Larceny Theft - From Building,"Theft, From Building, <$50",Open or Active,GOUGH ST \ PACIFIC AVE,26567000.0,Northern,Pacific Heights,2.0,2.0,37.794399,-122.426514,POINT (-122.426513672 37.794399261),2026/01/06 09:37:36 AM,2026/01/07 10:00:45 AM,Larceny
93948,153764103012,2025/12/31 08:00:00 PM,2025/12/31,20:00,2025,Wednesday,2026/01/06 02:32:00 PM,1537641,260009989,260062103.0,II,Initial,NaN,3012,Robbery,Robbery - Street,"Robbery, Street or Public Place, W/ Knife",Open or Active,20TH ST \ MISSION ST,24144000.0,Mission,Mission,9.0,9.0,37.758633,-122.419052,POINT (-122.419052124 37.75863266),2026/01/07 09:37:20 AM,2026/01/08 09:59:15 AM,Robbery
93949,153764104134,2025/12/31 08:00:00 PM,2025/12/31,20:00,2025,Wednesday,2026/01/06 02:32:00 PM,1537641,260009989,260062103.0,II,Initial,NaN,4134,Assault,Simple Assault,Battery,Open or Active,20TH ST \ MISSION ST,24144000.0,Mission,Mission,9.0,9.0,37.758633,-122.419052,POINT (-122.419052124 37.75863266),2026/01/07 09:37:20 AM,2026/01/08 09:59:15 AM,Assault
93952,153776807026,2025/12/31 05:10:00 PM,2025/12/31,17:10,2025,Wednesday,2026/01/06 02:27:00 PM,1537768,260009945,260062083.0,VI,Vehicle Initial,NaN,7026,Motor Vehicle Theft,Motor Vehicle Theft,"Vehicle, Stolen, Other Vehicle",Open or Active,DUBOCE AVE \ WOODWARD ST,24398000.0,Mission,Mission,9.0,9.0,37.769917,-122.420937,POINT (-122.420936584 37.769916534),2026/01/08 09:37:13 AM,2026/01/09 09:57:37 AM,Motor Vehicle Theft
93954,153815806303,2025/12/31 03:51:00 AM,2025/12/31,03:51,2025,Wednesday,2026/01/08 06:35:00 PM,1538158,260014518,260082761.0,II,Initial,NaN,6303,Larceny Theft,Larceny Theft - From Building,"Theft, From Building, $200-$950",Open or Active,CORBETT AVE \ DANVERS ST,26189000.0,Park,Castro/Upper Market,8.0,8.0,37.761280,-122.444008,POINT (-122.444007874 37.76128006),2026/01/09 09:37:35 AM,2026/01/10 09:57:31 AM,Larceny

In [594]:
filtered_df["Report Type Description"].value_counts()

Initial            20393
Vehicle Initial     4644
Name: Report Type Description, dtype: int64

In [595]:
filtered_df.head(3)

,Row ID,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,data_as_of,data_loaded_at,Consolidated Category
5,151652107026,2025/01/01 08:00:00 PM,2025/01/01,20:00,2025,Wednesday,2025/10/04 09:06:00 AM,1516521,250558736,252770881.0,VI,Vehicle Initial,NaN,7026,Motor Vehicle Theft,Motor Vehicle Theft,"Vehicle, Stolen, Other Vehicle",Open or Active,FELL ST \ VAN NESS AVE,24448000.0,Southern,Hayes Valley,5.0,5.0,37.776367,-122.419510,POINT (-122.419509888 37.776367188),2025/10/05 09:35:21 AM,2025/10/06 09:56:49 AM,Motor Vehicle Theft
18,153673706243,2025/01/01 06:00:00 PM,2025/01/01,18:00,2025,Wednesday,2026/01/02 01:32:00 PM,1536737,260002739,260021707.0,II,Initial,NaN,6243,Larceny Theft,Larceny - From Vehicle,"Theft, From Locked Vehicle, $200-$950",Open or Active,GEARY BLVD \ WOOD ST,26905000.0,Richmond,Lone Mountain/USF,2.0,1.0,37.782177,-122.449051,POINT (-122.449050903 37.782176971),2026/01/03 09:36:05 AM,2026/01/04 09:56:27 AM,Larceny
22,153876807021,2025/01/01 08:00:00 PM,2025/01/01,20:00,2025,Wednesday,2026/01/11 06:00:00 PM,1538768,260020220,260112501.0,VI,Vehicle Initial,NaN,7021,Motor Vehicle Theft,Motor Vehicle Theft,"Vehicle, Stolen, Auto",Open or Active,24TH ST \ DIAMOND ST,25760000.0,Mission,Noe Valley,8.0,8.0,37.751152,-122.436302,POINT (-122.436302185 37.751152039),2026/01/12 09:38:08 AM,2026/01/13 10:06:12 AM,Motor Vehicle Theft

In [596]:
# only keep the columns we need
filtered_df = filtered_df[['Incident ID', 'Consolidated Category', 'Latitude', 'Longitude']]
filtered_df.head(3)

    Incident ID Consolidated Category   Latitude   Longitude
5       1516521   Motor Vehicle Theft  37.776367 -122.419510
18      1536737               Larceny  37.782177 -122.449051
22      1538768   Motor Vehicle Theft  37.751152 -122.436302

In [597]:
import geopandas as gpd
from shapely.geometry import Point

In [598]:
# create GeoDataFrame from your incident coordinates
geometry = [Point(xy) for xy in zip(filtered_df['Longitude'], filtered_df['Latitude'])]
gdf_incidents = gpd.GeoDataFrame(filtered_df, geometry=geometry, crs='EPSG:4326')

In [599]:
# load census tract GeoJSON
census_tracts = gpd.read_file('../../data/basemap.geojson')

In [600]:
# spatial join to get tract info for each incident
df_new = gpd.sjoin(gdf_incidents, census_tracts, 
                                  how='left', predicate='within')

In [601]:
df_new.head(3)

,Incident ID,Consolidated Category,Latitude,Longitude,geometry,index_right,name,tract
5,1516521,Motor Vehicle Theft,37.776367,-122.419510,POINT (-122.41951 37.77637),168,124.05,012405
18,1536737,Larceny,37.782177,-122.449051,POINT (-122.44905 37.78218),27,157.01,015701
22,1538768,Motor Vehicle Theft,37.751152,-122.436302,POINT (-122.43630 37.75115),62,213,021300

In [602]:
# only keep columns we need
df_new = df_new[['Consolidated Category', 'name']]

In [603]:
# rename the columns
df_new = df_new.rename(columns={'Consolidated Category': 'Category', 'name': 'Area'})
df_new.head(3)

               Category    Area
5   Motor Vehicle Theft  124.05
18              Larceny  157.01
22  Motor Vehicle Theft     213

In [604]:
# reset the index
df_new = df_new.reset_index(drop=True)

In [605]:
# get shape of the final dataframe
print(df_new.shape)

(25037, 2)

In [606]:
# count the number of incidents by category and area
df_count = df_new.groupby(['Area', 'Category']).size().reset_index(name='Count')
df_count.head(3)

     Area  Category  Count
0  101.01   Assault     44
1  101.01  Burglary     16
2  101.01   Larceny    123

In [607]:
# change the columns to area and , and the values to the count of each category
df_pivot = df_count.pivot(index='Area', columns='Category', values='Count').fillna(0).reset_index()
# drop Category
df_pivot = df_pivot.rename_axis(None, axis=1)
# reset index
df_pivot = df_pivot.reset_index(drop=True)
df_pivot.head()

     Area  Assault  Burglary  Larceny  Motor Vehicle Theft  Robbery
0  101.01     44.0      16.0    123.0                 20.0     15.0
1  101.02     11.0       7.0     29.0                  5.0      4.0
2  102.01      3.0       8.0     11.0                  9.0      1.0
3  102.02     18.0       5.0     42.0                  8.0      4.0
4     103      8.0      14.0     25.0                  9.0      0.0

In [608]:
# keep as integers
df_pivot['Assault'] = df_pivot['Assault'].astype(int)
df_pivot['Burglary'] = df_pivot['Burglary'].astype(int)
df_pivot['Larceny'] = df_pivot['Larceny'].astype(int)   
df_pivot['Motor Vehicle Theft'] = df_pivot['Motor Vehicle Theft'].astype(int)
df_pivot['Robbery'] = df_pivot['Robbery'].astype(int)
df_pivot.head()

     Area  Assault  Burglary  Larceny  Motor Vehicle Theft  Robbery
0  101.01       44        16      123                   20       15
1  101.02       11         7       29                    5        4
2  102.01        3         8       11                    9        1
3  102.02       18         5       42                    8        4
4     103        8        14       25                    9        0

In [609]:
# convert numeric columns to proper data types
numeric_columns = ['Assault', 'Burglary', 'Larceny', 'Motor Vehicle Theft', 'Robbery']
df_pivot[numeric_columns] = df_pivot[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'assault': df_pivot.set_index('Area')['Assault'].to_dict(),
    'burglary': df_pivot.set_index('Area')['Burglary'].to_dict(),
    'larceny': df_pivot.set_index('Area')['Larceny'].to_dict(),
    'motor vehicle theft': df_pivot.set_index('Area')['Motor Vehicle Theft'].to_dict(),
    'robbery': df_pivot.set_index('Area')['Robbery'].to_dict()
}

# convert to JSON and save to file
import json

with open('./just-crime.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'just-crime.json'")

JSON file saved as 'just-crime.json'

In [610]:
import json
import pandas as pd

# load files
with open('just-crime.json', 'r') as f:
    crime_data = json.load(f)
with open('population.json', 'r') as f:
    population_data = json.load(f)

# create final DataFrame
crime_areas = set().union(*[crime_data[ct].keys() for ct in crime_data])
population_areas = set(population_data['value'].keys())
common_areas = crime_areas.intersection(population_areas)

result_data = []
for area in common_areas:
    row = {'Area': area}
    for crime_type in crime_data:
        row[crime_type.title()] = crime_data[crime_type].get(area, 0)
    row['Total Population'] = population_data['value'][area]
    result_data.append(row)

df_final = pd.DataFrame(result_data).sort_values('Area').reset_index(drop=True)

In [611]:
df_final

,Area,Assault,Burglary,Larceny,Motor Vehicle Theft,Robbery,Total Population
0,101.01,44,16,123,20,15,1911
1,101.02,11,7,29,5,4,1917
2,102.01,3,8,11,9,1,2650
3,102.02,18,5,42,8,4,1839
4,103,8,14,25,9,0,3824
...,...,...,...,...,...,...,...
236,9802,0,0,2,0,0,160
237,9803,39,26,76,33,8,58
238,9805.01,18,0,9,9,6,146
239,9806,13,10,15,17,1,1295
240,9809,109,52,137,65,31,439

In [612]:
# convert numeric columns to proper data types
numeric_columns = ['Assault', 'Burglary', 'Larceny', 'Motor Vehicle Theft', 'Robbery', 'Total Population']
df_final[numeric_columns] = df_final[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'assault': df_final.set_index('Area')['Assault'].to_dict(),
    'burglary': df_final.set_index('Area')['Burglary'].to_dict(),
    'larceny': df_final.set_index('Area')['Larceny'].to_dict(),
    'motor vehicle theft': df_final.set_index('Area')['Motor Vehicle Theft'].to_dict(),
    'robbery': df_final.set_index('Area')['Robbery'].to_dict(),
    'population': df_final.set_index('Area')['Total Population'].to_dict()
}

# convert to JSON and save to file
import json

with open('../../data/crime.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'crime.json'")

JSON file saved as 'crime.json'

## Checking things

In [613]:
# isolate all rows in df from Bayview Hunters Point
bayview_df = df[df['Analysis Neighborhood'] == 'Bayview Hunters Point']

In [614]:
bayview_df

,Row ID,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Incident ID,Incident Number,CAD Number,Report Type Code,Report Type Description,Filed Online,Incident Code,Incident Category,Incident Subcategory,Incident Description,Resolution,Intersection,CNN,Police District,Analysis Neighborhood,Supervisor District,Supervisor District 2012,Latitude,Longitude,Point,data_as_of,data_loaded_at
7,152607209262,2025/01/01 01:55:00 AM,2025/01/01,01:55,2025,Wednesday,2025/11/08 02:04:00 AM,1526072,256122913,NaN,II,Coplogic Initial,True,9262,Forgery And Counterfeiting,Forgery And Counterfeiting,Forgery & Counterfeiting (general),Open or Active,KISKA RD \ REARDON RD,20058000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.730015,-122.377205,POINT (-122.377204895 37.730014801),2025/11/14 09:39:20 AM,2025/11/15 09:55:43 AM
8,152670268020,2025/01/01 11:00:00 AM,2025/01/01,11:00,2025,Wednesday,2025/11/17 11:54:00 AM,1526702,250647602,253211330.0,II,Initial,NaN,68020,Miscellaneous Investigation,Miscellaneous Investigation,Miscellaneous Investigation,Open or Active,AMADOR ST \ ILLINOIS ST,54330000.0,Central,Bayview Hunters Point,10.0,10.0,37.745758,-122.386063,POINT (-122.386062622 37.745758057),2025/11/18 09:38:25 AM,2025/11/19 10:19:36 AM
23,154019771000,2025/01/01 12:00:00 AM,2025/01/01,00:00,2025,Wednesday,2026/01/15 04:05:00 PM,1540197,260028224,260152330.0,II,Initial,NaN,71000,Lost Property,Lost Property,Lost Property,Open or Active,COMMER CT \ GARLINGTON CT,20138000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.732353,-122.384499,POINT (-122.384498596 37.73235321),2026/01/16 09:36:07 AM,2026/01/17 09:56:59 AM
39,145113451040,2025/01/01 01:10:00 AM,2025/01/01,01:10,2025,Wednesday,2025/01/01 01:45:00 AM,1451134,250000317,250010389.0,II,Initial,NaN,51040,Non-Criminal,Non-Criminal,Aided Case,Open or Active,MARIN ST \ MICHIGAN ST,23529000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.749123,-122.385490,POINT (-122.385490417 37.74912262),2025/06/12 10:07:02 AM,2025/06/13 09:52:57 AM
40,145113468020,2025/01/01 01:10:00 AM,2025/01/01,01:10,2025,Wednesday,2025/01/01 01:45:00 AM,1451134,250000317,250010389.0,II,Initial,NaN,68020,Miscellaneous Investigation,Miscellaneous Investigation,Miscellaneous Investigation,Open or Active,MARIN ST \ MICHIGAN ST,23529000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.749123,-122.385490,POINT (-122.385490417 37.74912262),2025/06/12 10:07:02 AM,2025/06/13 09:52:57 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93823,153619419010,2025/12/31 08:38:00 AM,2025/12/31,08:38,2025,Wednesday,2025/12/31 08:38:00 AM,1536194,250727840,253650734.0,II,Initial,NaN,19010,Disorderly Conduct,Disorderly Conduct,"Public Nuisance, Committing",Cite or Arrest Adult,LANE ST \ YOSEMITE AVE,20494000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.727913,-122.393532,POINT (-122.393531799 37.727912903),2026/01/01 09:38:48 AM,2026/01/02 09:58:12 AM
93831,153636865010,2025/12/31 04:27:00 PM,2025/12/31,16:27,2025,Wednesday,2025/12/31 04:27:00 PM,1536368,250728791,253652129.0,II,Initial,NaN,65010,Traffic Violation Arrest,Traffic Violation Arrest,Traffic Violation Arrest,Cite or Arrest Adult,03RD ST \ MENDELL ST \ PALOU AVE,33269000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.734013,-122.390968,POINT (-122.390968323 37.734012604),2026/01/01 09:38:48 AM,2026/01/02 09:58:12 AM
93836,153619427199,2025/12/31 08:38:00 AM,2025/12/31,08:38,2025,Wednesday,2025/12/31 08:38:00 AM,1536194,250727840,253650734.0,II,Initial,NaN,27199,Other Miscellaneous,Loitering,Lodging Without Permission,Cite or Arrest Adult,LANE ST \ YOSEMITE AVE,20494000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.727913,-122.393532,POINT (-122.393531799 37.727912903),2026/01/01 09:38:48 AM,2026/01/02 09:58:12 AM
93860,153619419060,2025/12/31 08:38:00 AM,2025/12/31,08:38,2025,Wednesday,2025/12/31 08:38:00 AM,1536194,250727840,253650734.0,II,Initial,NaN,19060,Disorderly Conduct,Loitering,Obstructing Public Thoroughfare (or 647(c) PC),Cite or Arrest Adult,LANE ST \ YOSEMITE AVE,20494000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.727913,-122.393532,POINT (-122.393531799 37.727912903),2026/01/01 09:38:48 AM,2026/01/02 09:58:12 AM
93879,153637765010,2025/12/31 11:04:00 PM,2025/12/31,23:04,2025,Wednesday,2025/12/31 11:04:00 PM,1536377,250729181,253653237.0,II,Initial,NaN,65010,Traffic Violation Arrest,Traffic Violation Arrest,Traffic Violation Arrest,Cite or Arrest Adult,INGALLS ST \ KISKA RD,20077000.0,Bayview,Bayview Hunters Point,10.0,10.0,37.731110,-122.379555,POINT (-122.379554749 37.731109619),2026/01/01 09:38:48 AM,2026/01/02 09:58:12 AM

In [615]:
# show me rows where the category is "Assault"

bayview_df[bayview_df['Incident Category'] == 'Assault'].shape[0] 

# calculate the total number of incidents in Bayview Hunters Point per 1,000 residents, knowing that the population is 37735.0

total_incidents = bayview_df.shape[0]

incidents_per_1000 = (total_incidents / 37735.0) * 1000

print(f"Total incidents in Bayview Hunters Point: {total_incidents}")

Total incidents in Bayview Hunters Point: 6066

In [616]:
bayview_df.shape[0]

6066

In [617]:
# in df, only keep the rows where the