In [121]:
import pandas as pd

In [122]:
# import data, using the dataset I used for age
df = pd.read_csv('./ACSDP5Y2024.DP05-Data.csv')

In [123]:
df.head(3)

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0104PM,DP05_0105PE,DP05_0105PM,DP05_0106PE,DP05_0106PM,DP05_0107PE,DP05_0107PM,DP05_0108PE,DP05_0108PM,Unnamed: 434
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,1400000US06075010101,Census Tract 101.01; San Francisco County; Cal...,1911,285,1025,197,886,165,115.7,27.3,...,1.8,(X),(X),1437,(X),55.1,8.2,44.9,8.2,NaN
2,1400000US06075010102,Census Tract 101.02; San Francisco County; Cal...,1917,339,855,170,1062,323,80.5,32.8,...,1.1,(X),(X),1534,(X),47.1,9.3,52.9,9.3,NaN

In [124]:
# drop the first column
df = df.drop(df.columns[0], axis=1)
df.head(3)

,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,...,DP05_0104PM,DP05_0105PE,DP05_0105PM,DP05_0106PE,DP05_0106PM,DP05_0107PE,DP05_0107PM,DP05_0108PE,DP05_0108PM,Unnamed: 434
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Under...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,285,1025,197,886,165,115.7,27.3,21,...,1.8,(X),(X),1437,(X),55.1,8.2,44.9,8.2,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,339,855,170,1062,323,80.5,32.8,57,...,1.1,(X),(X),1534,(X),47.1,9.3,52.9,9.3,NaN

In [125]:
# change NAME to Area
df = df.rename(columns={'NAME': 'Area'})
df.head(3)

,Area,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,DP05_0005E,...,DP05_0104PM,DP05_0105PE,DP05_0105PM,DP05_0106PE,DP05_0106PM,DP05_0107PE,DP05_0107PM,DP05_0108PE,DP05_0108PM,Unnamed: 434
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Under...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,285,1025,197,886,165,115.7,27.3,21,...,1.8,(X),(X),1437,(X),55.1,8.2,44.9,8.2,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,339,855,170,1062,323,80.5,32.8,57,...,1.1,(X),(X),1534,(X),47.1,9.3,52.9,9.3,NaN

In [126]:
# drop the margin columns
df = df[df.columns.drop(list(df.filter(regex='M')))]
df.head(3)

,Area,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,DP05_0009E,...,DP05_0100PE,DP05_0101PE,DP05_0102PE,DP05_0103PE,DP05_0104PE,DP05_0105PE,DP05_0106PE,DP05_0107PE,DP05_0108PE,Unnamed: 434
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex r...,Estimate!!SEX AND AGE!!Total population!!Under...,Estimate!!SEX AND AGE!!Total population!!5 to ...,Estimate!!SEX AND AGE!!Total population!!10 to...,Estimate!!SEX AND AGE!!Total population!!15 to...,Estimate!!SEX AND AGE!!Total population!!20 to...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,1025,886,115.7,21,15,9,111,66,...,0.0,3.2,2.0,0.0,2.0,(X),1437,55.1,44.9,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,855,1062,80.5,57,50,52,144,85,...,0.6,0.0,1.1,0.0,1.1,(X),1534,47.1,52.9,NaN

In [127]:
# rename columns
column_mapping = {}
for i, col in enumerate(df.columns):
    if i < len(df.iloc[0]):  # Make sure we don't go out of bounds
        column_mapping[col] = df.iloc[0, i]

df = df.rename(columns=column_mapping)
df.head(3)

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,...,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",NaN
0,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex r...,Estimate!!SEX AND AGE!!Total population!!Under...,Estimate!!SEX AND AGE!!Total population!!5 to ...,Estimate!!SEX AND AGE!!Total population!!10 to...,Estimate!!SEX AND AGE!!Total population!!15 to...,Estimate!!SEX AND AGE!!Total population!!20 to...,...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!HISPANIC OR LATINO AND RACE!!Total po...,Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...",NaN
1,Census Tract 101.01; San Francisco County; Cal...,1911,1025,886,115.7,21,15,9,111,66,...,0.0,3.2,2.0,0.0,2.0,(X),1437,55.1,44.9,NaN
2,Census Tract 101.02; San Francisco County; Cal...,1917,855,1062,80.5,57,50,52,144,85,...,0.6,0.0,1.1,0.0,1.1,(X),1534,47.1,52.9,NaN

In [128]:
# remove the first row
df = df.drop(df.index[0])  
df = df.reset_index(drop=True)
df.head(3)

,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!Under 5 years,Estimate!!SEX AND AGE!!Total population!!5 to 9 years,Estimate!!SEX AND AGE!!Total population!!10 to 14 years,Estimate!!SEX AND AGE!!Total population!!15 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 24 years,...,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some Other Race alone,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races,Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races including Some Other Race,"Percent!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or More Races!!Two races excluding Some Other Race, and three or more races",Percent!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",NaN
0,Census Tract 101.01; San Francisco County; Cal...,1911,1025,886,115.7,21,15,9,111,66,...,0.0,3.2,2.0,0.0,2.0,(X),1437,55.1,44.9,NaN
1,Census Tract 101.02; San Francisco County; Cal...,1917,855,1062,80.5,57,50,52,144,85,...,0.6,0.0,1.1,0.0,1.1,(X),1534,47.1,52.9,NaN
2,Census Tract 102.01; San Francisco County; Cal...,2650,1321,1329,99.4,94,47,24,70,175,...,0.0,0.4,7.1,0.3,6.8,(X),2085,48.7,51.3,NaN

In [129]:
# change Geographic Area Name to Area
df = df.rename(columns={'Geographic Area Name': 'Area'})

In [130]:
# keep area and total population columns
df = df[['Area', 'Estimate!!SEX AND AGE!!Total population']]
df.head(3)

,Area,Estimate!!SEX AND AGE!!Total population
0,Census Tract 101.01; San Francisco County; Cal...,1911
1,Census Tract 101.02; San Francisco County; Cal...,1917
2,Census Tract 102.01; San Francisco County; Cal...,2650

In [131]:
# only keep numbers for the area column
df['Area'] = df['Area'].str.replace(r'.*Census Tract\s+', '', regex=True)  # remove everything before tract number
df['Area'] = df['Area'].str.replace(r';.*', '', regex=True)  # remove everything after semicolon
df['Area'] = df['Area'].str.strip()  # remove any extra whitespace
df

        Area Estimate!!SEX AND AGE!!Total population
0     101.01                                    1911
1     101.02                                    1917
2     102.01                                    2650
3     102.02                                    1839
4        103                                    3824
..       ...                                     ...
239  9805.01                                     146
240     9806                                    1295
241     9809                                     439
242     9901                                       0
243     9902                                       0

[244 rows x 2 columns]

In [132]:
# change the total population column name
df = df.rename(columns={'Estimate!!SEX AND AGE!!Total population': 'Total Population'})
df.head(3)

     Area Total Population
0  101.01             1911
1  101.02             1917
2  102.01             2650

In [133]:
# convert numeric columns to proper data types
numeric_columns = ['Total Population']
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

# create the dictionary in the format you want
result_dict = {
    'value': df.set_index('Area')['Total Population'].to_dict(),
}

# convert to JSON and save to file
import json

with open('../../data/population.json', 'w') as f:
    json.dump(result_dict, f, indent=2)

print("JSON file saved as 'population.json'")

JSON file saved as 'population.json'

In [134]:
# export the final dataframe to CSV
df.to_csv('./population.csv', index=False)

In [135]:
lookup_df = pd.read_csv('../../data/lookup.csv')

In [136]:
lookup_df.dtypes

tract           float64
neighborhood     object
note             object
dtype: object

In [137]:
lookup_df['tract'] = lookup_df['tract'].astype(str)

In [138]:
# keep the rows where neighborhood is Tenderloin
tenderloin_df = lookup_df[lookup_df['neighborhood'] == 'Tenderloin']

# join matching rows on tract (lookup_df) and Area (population df)
tenderloin_df = pd.merge(tenderloin_df, df, left_on='tract', right_on='Area')

In [139]:
tenderloin_df['Total Population'].sum()

32104

In [140]:
df['Total Population'].sum()

830235

Info for population totals on pages:

In [141]:
# read in lookup table 

lookup_df = pd.read_csv('../../data/lookup.csv')
lookup_df.head(3)

    tract           neighborhood   note
0  9809.0  Bayview Hunters Point  empty
1  9806.0  Bayview Hunters Point  empty
2   612.0  Bayview Hunters Point  empty

In [142]:
# replace .0 and .00 at the end of the tract numbers with empty string

lookup_df['tract'] = lookup_df['tract'].astype(str).str.replace(r'\.0+$', '', regex=True)
lookup_df['tract'] = lookup_df['tract'].astype(str).str.replace(r'\.00+$', '', regex=True)
lookup_df.head(3)

  tract           neighborhood   note
0  9809  Bayview Hunters Point  empty
1  9806  Bayview Hunters Point  empty
2   612  Bayview Hunters Point  empty

In [143]:
# remove note column 

lookup_df = lookup_df.drop(columns=['note'])

In [144]:
# isolate the rows for Mission 

mission_df = lookup_df[lookup_df['neighborhood'] == 'Mission']

mission_df

      tract neighborhood
92   229.03      Mission
93   229.02      Mission
94   229.01      Mission
95   228.03      Mission
96   228.01      Mission
97   228.02      Mission
98   207.01      Mission
99   208.01      Mission
100  201.01      Mission
101     210      Mission
102     209      Mission
103  207.02      Mission
104  202.02      Mission
105  202.01      Mission
106  201.02      Mission
107     177      Mission
108  208.02      Mission

In [145]:
mission_ids = mission_df['tract'].astype(str).tolist()
mission_ids

['229.03',
 '229.02',
 '229.01',
 '228.03',
 '228.01',
 '228.02',
 '207.01',
 '208.01',
 '201.01',
 '210',
 '209',
 '207.02',
 '202.02',
 '202.01',
 '201.02',
 '177',
 '208.02']

In [146]:
# look through df and find the rows where Area is in mission_ids
mission_population_df = df[df['Area'].isin(mission_ids)]

mission_population_df

       Area  Total Population
87      177              2946
93   201.01              3943
94   201.02              3463
95   202.01              1905
96   202.02              3979
103  207.01              3357
104  207.02              1995
105  208.01              3767
106  208.02              2188
107     209              3746
108     210              3609
120  228.01              4765
121  228.02              2103
122  228.03              4117
123  229.01              4542
124  229.02              1891
125  229.03              2798

In [147]:
mission_population_df['Total Population'].sum()

55114

In [148]:
bayview_df = lookup_df[lookup_df['neighborhood'] == 'Bayview Hunters Point']
bayview_df

     tract           neighborhood
0     9809  Bayview Hunters Point
1     9806  Bayview Hunters Point
2      612  Bayview Hunters Point
3      610  Bayview Hunters Point
4   230.03  Bayview Hunters Point
5      233  Bayview Hunters Point
6      232  Bayview Hunters Point
7   231.03  Bayview Hunters Point
8   231.02  Bayview Hunters Point
9   230.01  Bayview Hunters Point
10     234  Bayview Hunters Point

In [149]:
bayview_ids = bayview_df['tract'].astype(str).tolist()
bayview_ids

['9809',
 '9806',
 '612',
 '610',
 '230.03',
 '233',
 '232',
 '231.03',
 '231.02',
 '230.01',
 '234']

In [150]:
bayview_population_df = df[df['Area'].isin(bayview_ids)]

bayview_population_df

       Area  Total Population
126  230.01              5108
127  230.03              3812
128  231.02              3231
129  231.03              4545
130     232              3570
131     233              3818
132     234              3536
222     610              4295
225     612              4086
240    9806              1295
241    9809               439

In [151]:
bayview_population_df['Total Population'].sum()

37735

In [152]:
sunset = lookup_df[(lookup_df['neighborhood'] == 'Inner Sunset') | (lookup_df['neighborhood'] == 'Sunset/Parkside')]

sunset

      tract     neighborhood
66   301.01     Inner Sunset
67   303.02     Inner Sunset
68   303.01     Inner Sunset
69   302.02     Inner Sunset
70   302.01     Inner Sunset
71   301.02     Inner Sunset
191     353  Sunset/Parkside
192  352.02  Sunset/Parkside
193  352.01  Sunset/Parkside
194  351.02  Sunset/Parkside
195  351.01  Sunset/Parkside
196     354  Sunset/Parkside
197  326.01  Sunset/Parkside
198     331  Sunset/Parkside
199  330.02  Sunset/Parkside
200  330.01  Sunset/Parkside
201  328.01  Sunset/Parkside
202     327  Sunset/Parkside
203  326.02  Sunset/Parkside
204  329.01  Sunset/Parkside
205  329.02  Sunset/Parkside
206  328.02  Sunset/Parkside

In [153]:
sunset_ids = sunset['tract'].astype(str).tolist()
sunset_ids

['301.01',
 '303.02',
 '303.01',
 '302.02',
 '302.01',
 '301.02',
 '353',
 '352.02',
 '352.01',
 '351.02',
 '351.01',
 '354',
 '326.01',
 '331',
 '330.02',
 '330.01',
 '328.01',
 '327',
 '326.02',
 '329.01',
 '329.02',
 '328.02']

In [154]:
sunset_population_df = df[df['Area'].isin(sunset_ids)]

sunset_population_df

       Area  Total Population
160  301.01              4389
161  301.02              5120
162  302.01              3841
163  302.02              4082
164  303.01              6160
165  303.02              3552
180  326.01              4338
181  326.02              4118
182     327              6573
183  328.01              4021
184  328.02              4268
185  329.01              6013
186  329.02              3720
187  330.01              3911
188  330.02              4015
189     331              3755
193  351.01              3748
194  351.02              3755
195  352.01              5020
196  352.02              4188
197     353              6525
198     354              7140

In [155]:
sunset_population_df['Total Population'].sum()

102252

In [156]:
richmond = lookup_df[(lookup_df['neighborhood'] == 'Inner Richmond') | (lookup_df['neighborhood'] == 'Outer Richmond')]

richmond

      tract    neighborhood
61   452.02  Inner Richmond
62   452.01  Inner Richmond
63      451  Inner Richmond
64      402  Inner Richmond
65      401  Inner Richmond
143     476  Outer Richmond
144  479.04  Outer Richmond
145  478.01  Outer Richmond
146  426.02  Outer Richmond
147  426.01  Outer Richmond
148  479.03  Outer Richmond
149  479.02  Outer Richmond
150     427  Outer Richmond
151  477.01  Outer Richmond
152  478.02  Outer Richmond
153  477.02  Outer Richmond

In [157]:
richmond_ids = richmond['tract'].astype(str).tolist()
richmond_ids

['452.02',
 '452.01',
 '451',
 '402',
 '401',
 '476',
 '479.04',
 '478.01',
 '426.02',
 '426.01',
 '479.03',
 '479.02',
 '427',
 '477.01',
 '478.02',
 '477.02']

In [158]:
richmond_population_df = df[df['Area'].isin(richmond_ids)]

richmond_population_df

       Area  Total Population
199     401              4315
200     402              4719
201  426.01              4342
202  426.02              3202
203     427              5134
205     451              4713
206  452.01              3045
207  452.02              3332
208     476              5098
209  477.01              4724
210  477.02              3135
211  478.01              4132
212  478.02              3581
213  479.02              3236
214  479.03              3348
215  479.04              3077

In [159]:
richmond_population_df['Total Population'].sum()

63133